# 超稳定配置 - 确保长期稳定训练
model_type: AdvancedFactorForecastingTCNAttention
input_dim: 100
hidden_dim: 384    # 进一步减小
num_layers: 6      # 减少层数
num_heads: 6       # 减少注意力头数
tcn_kernel_size: 3
tcn_dilation_factor: 2
dropout_rate: 0.1
attention_dropout: 0.05
target_columns: [intra30m, nextT1d, ema1d]
sequence_length: 30        # 减小序列长度
epochs: 200
batch_size: 512           # 更小的批次大小
fixed_batch_size: 512
learning_rate: 0.0001
weight_decay: 0.01
gradient_clip_norm: 1.0
use_mixed_precision: true
accumulation_steps: 4     # 增加梯度累积补偿小批次
use_adaptive_batch_size: false
num_workers: 0
pin_memory: false
use_distributed: false
auto_resume: true
log_level: INFO
ic_report_interval: 7200  # 2小时报告
enable_ic_reporting: true
checkpoint_frequency: 5
save_all_checkpoints: false
output_dir: /nas/factor_forecasting/outputs
data_dir: /nas/feature_v2_10s
train_start_date: 2018-01-02
train_end_date: 2018-10-31   # 使用前10个月数据
val_start_date: 2018-11-01
val_end_date: 2018-11-30
test_start_date: 2018-12-01
test_end_date: 2018-12-31
enforce_next_year_prediction: false
enable_yearly_rolling: false
min_train_years: 1
rolling_window_years: 1
shuffle_buffer_size: 256

# 内存优化参数
max_memory_usage: 16      # 严格限制GPU内存
streaming_chunk_size: 10000
enable_memory_mapping: false
enable_gradient_checkpointing: true
