name: factor_forecast
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Deep Learning Framework
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  
  # Data Processing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Utilities
  - pyyaml>=6.0
  - tqdm>=4.64.0
  - python-dotenv>=0.19.0
  - requests>=2.28.0
  
  # Testing
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  
  # Package manager
  - pip
  - pip:
    # Web API and Services
    - fastapi>=0.100.0
    - "uvicorn[standard]>=0.20.0"
    - pydantic>=2.0.0
    - redis>=4.0.0
    - prometheus-client>=0.15.0
    
    # Data Processing
    - pyarrow>=8.0.0
    - fastparquet>=0.8.0
    - pandasql>=0.7.3
    
    # Visualization and Monitoring
    - tensorboard>=2.12.0
    - plotly>=5.0.0
    
    # Experiment Tracking
    - optuna>=3.0.0
    - wandb>=0.15.0
    - mlflow>=2.0.0
    
    # Development Tools
    - black>=23.0.0
    - flake8>=6.0.0
    - mypy>=1.0.0
    - isort>=5.12.0
    - pre-commit>=3.0.0
    
    # Jupyter Development
    - jupyter>=1.0.0
    - ipython>=8.0.0
    - jupyterlab>=4.0.0
    
    # Production and Deployment
    - gunicorn>=21.0.0
    - supervisor>=4.2.0
    - docker>=6.0.0
    
    # Monitoring and Logging
    - structlog>=23.0.0
    - sentry-sdk>=1.25.0
    
    # Utilities
    - click>=8.0.0
    - colorlog>=6.9.0
    
    # GPU Support
    - nvidia-ml-py3>=7.352.0 