model_type: AdvancedFactorForecastingTCNAttention
input_dim: 100
hidden_dim: 768
num_layers: 12
num_heads: 16
tcn_kernel_size: 7
tcn_dilation_factor: 2
dropout_rate: 0.15
attention_dropout: 0.1
target_columns: [intra30m, nextT1d, ema1d]
sequence_length: 60
epochs: 100
batch_size: 2048
fixed_batch_size: 2048
learning_rate: 0.0002
weight_decay: 0.01
gradient_clip_norm: 1.0
use_mixed_precision: true
accumulation_steps: 1
use_adaptive_batch_size: false
adaptive_batch_size: false
num_workers: 4
pin_memory: true
prefetch_factor: 2
use_distributed: true
auto_resume: true
log_level: INFO
ic_report_interval: 7200
enable_ic_reporting: true
checkpoint_frequency: 10
save_all_checkpoints: false
output_dir: /nas/factor_forecasting/outputs
data_dir: /nas/feature_v2_10s
train_start_date: 2018-01-02
train_end_date: 2018-10-31
val_start_date: 2018-11-01
val_end_date: 2018-12-31
test_start_date: 2019-01-01
test_end_date: 2019-12-31
enforce_next_year_prediction: true
enable_yearly_rolling: false
min_train_years: 1
rolling_window_years: 1
shuffle_buffer_size: 512
